.\" Copyright (C) 2019 VirtualSquare. Project Leader: Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" as published by the Free Software Foundation, either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.
.\"
.\" generated with Ronn-NG/v0.10.0
.\" http://github.com/apjanke/ronn-ng/tree/0.10.0-SNAPSHOT
.TH "IPLINK" "1" "August 2020" "VirtualSquare-VUOS"
.SH "NAME"
\fBiplink\fR \- add/delete generic interfaces
.SH "SYNOPSIS"
\fBiplink add\fR [ [ \fBname\fR ] \fINAME\fR ] [ \fBindex\fR \fIIDX\fR ] [ \fBdata\fR \fIDATA\fR ] \fBtype\fR \fITYPE\fR
.P
\fBiplink delete\fR [ \fIDEVICE\fR | \fBdev\fR \fIDEVICE\fR ] [ \fBindex\fR \fIIDX\fR ] [ \fBtype\fR \fITYPE\fR ]
.P
\fBiplink del\fR [ \fIDEVICE\fR | \fBdev\fR \fIDEVICE\fR ] [ \fBindex\fR \fIIDX\fR ] [ \fBtype\fR \fITYPE\fR ]
.SH "DESCRIPTION"
\fBiplink\fR allow users to add or delete interfaces whose types are not supported by \fBip\-link\fR(8)\.
.SS "iplink add"
\fBiplink add\fR adds a generic interface of type \fITYPE\fR\.
.TP
\fBname\fR \fINAME\fR
sets the name of the new interface\. (the tag \fBname\fR can be omitted)\.
.TP
\fBindex\fR \fIIDX\fR
specifies the desired index of the new virtual device\.
.TP
\fBdata\fR \fIDATA\fR
adds specific data to configure the interface\. The meaning depends upon the type of the interface\.
.SS "iplink del \-\- iplink delete"
\fBiplink del\fR or \fBiplink delete\fR deletes an interface\. At least one option between \fBdev\fR or \fBindex\fR must be selected\.
.TP
\fBdev\fR \fIDEVICE\fR
select the interface by its name\. (the tag \fBdev\fR can be omitted)\.
.TP
\fBindex\fR \fIIDX\fR
select the interface by its index\.
.TP
\fBtype\fR \fITYPE\fR
specify the interface type (currently ignored)\.
.SH "EXANPLE"
In a \fBumvu\fR session:
.IP "" 4
.nf
$ vu_insmod vunet
$ mount \-t vunetpicox none /dev/n
$ vustack /dev/n iplink add vde1 type vde data vxvde://234\.0\.0\.1
$ vustack /dev/n ip link
2090479455: loop: <UP> mtu 1500
    link/netrom 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
2090826453: vde1: <UP> mtu 1500
    link/netrom 80:00:47:2f:13:d8 brd ff:ff:ff:ff:ff:ff
.fi
.IP "" 0
.SH "SEE ALSO"
umvu(1), ip(8), ip\-link(8)
.SH "AUTHOR"
VirtualSquare\. Project leader: Renzo Davoli\.
